
  - name: "update packages."
    become: true
    apt:
      update_cache: yes
  - name: "upgrade packages"
    become: true
    apt:
      upgrade: yes
      
  - name: "Install node.js from nodesource"
    become: true
    shell: |
      curl -fsSL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      
    # sudo apt -y install nodejs

  - name: "Install Node.js 10"
    become: true
    apt: 
     name: ["nodejs"]
     state: latest
     update_cache: yes 
     
  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present